import {
    AvailabilityRules,
    BusinessPublicPageSettings,
    BusinessTemplateKey,
    BusinessTemplatePreset,
    BusinessWidgetSettings,
    NotificationSettings,
    WorkingHour,
} from "../interfaces/business.interface";

const weekTemplate = (startTime: string, endTime: string, weekendClosed: number[] = [0, 6]): WorkingHour[] => (
    Array.from({ length: 7 }, (_, dayOfWeek) => ({
        dayOfWeek,
        startTime,
        endTime,
        closed: weekendClosed.includes(dayOfWeek),
    }))
);

const createAvailabilityRules = (rules: AvailabilityRules): AvailabilityRules => ({ ...rules });
const createNotificationSettings = (settings: NotificationSettings): NotificationSettings => ({
    ...settings,
    enabledChannels: [...settings.enabledChannels],
    reminderLeadHours: [...settings.reminderLeadHours],
});
const createWidgetSettings = (settings: BusinessWidgetSettings): BusinessWidgetSettings => ({ ...settings });
const createPublicPageSettings = (settings: BusinessPublicPageSettings): BusinessPublicPageSettings => ({ ...settings });

export const businessTemplatePresets: BusinessTemplatePreset[] = [
    {
        key: "restaurant",
        label: "Restaurant Service",
        description: "Fast table-turn scheduling with short lead times and table-focused resource suggestions.",
        businessType: "restaurant",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 15,
            minAdvanceMinutes: 30,
            maxAdvanceDays: 60,
            bufferBeforeMinutes: 0,
            bufferAfterMinutes: 15,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("11:00", "22:00"),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email"],
            reminderLeadHours: [4, 24],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#B85C38",
            embedTitle: "Reserve Your Table",
            introMessage: "Pick a table time that works best for your party.",
            primaryActionLabel: "Book Table",
            showServiceSelector: true,
            showPartySize: true,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Reserve a Table at Our Restaurant",
            heroMessage: "Choose your preferred dining time and we will take care of the rest.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your reservation request is on its way. We will confirm the details shortly.",
        }),
        suggestedResources: [
            { name: "Main Dining Tables", resourceType: "table", capacity: 4, requiresApproval: false },
            { name: "Large Party Tables", resourceType: "table", capacity: 8, requiresApproval: true },
        ],
    },
    {
        key: "clinic",
        label: "Clinic Appointments",
        description: "Structured appointment slots with more notice, staff resources, and stronger approval defaults.",
        businessType: "clinic",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 30,
            minAdvanceMinutes: 120,
            maxAdvanceDays: 120,
            bufferBeforeMinutes: 10,
            bufferAfterMinutes: 10,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("08:00", "17:00", [0]),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email", "sms"],
            reminderLeadHours: [24, 72],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#2D6A8A",
            embedTitle: "Book an Appointment",
            introMessage: "Choose a practitioner, room, or visit slot.",
            primaryActionLabel: "Schedule Visit",
            showServiceSelector: true,
            showPartySize: false,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Book a Clinic Appointment",
            heroMessage: "Select the visit type and timing that best fits your care needs.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your appointment request has been received and will be confirmed soon.",
        }),
        suggestedResources: [
            { name: "Consultation Rooms", resourceType: "room", capacity: 1, requiresApproval: false },
            { name: "Practitioner Schedule", resourceType: "staff", capacity: 1, durationMinutes: 30, requiresApproval: false },
        ],
    },
    {
        key: "salon",
        label: "Salon Sessions",
        description: "Service-duration scheduling with stylist resources and moderate appointment buffers.",
        businessType: "salon",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 15,
            minAdvanceMinutes: 60,
            maxAdvanceDays: 90,
            bufferBeforeMinutes: 5,
            bufferAfterMinutes: 10,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("09:00", "19:00"),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email", "sms"],
            reminderLeadHours: [24],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#C46A5D",
            embedTitle: "Book a Salon Session",
            introMessage: "Pick a stylist or service and choose your preferred time.",
            primaryActionLabel: "Reserve Session",
            showServiceSelector: true,
            showPartySize: false,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Reserve Your Salon Visit",
            heroMessage: "Choose your service, stylist, and ideal time in just a few steps.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your salon booking request has been received.",
        }),
        suggestedResources: [
            { name: "Stylist Team", resourceType: "staff", capacity: 1, durationMinutes: 60, requiresApproval: false },
            { name: "Treatment Chairs", resourceType: "service", capacity: 1, durationMinutes: 45, requiresApproval: false },
        ],
    },
    {
        key: "consulting",
        label: "Consulting Sessions",
        description: "Longer planning windows with low-capacity appointment blocks for advisors and consultants.",
        businessType: "consulting",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 30,
            minAdvanceMinutes: 240,
            maxAdvanceDays: 180,
            bufferBeforeMinutes: 15,
            bufferAfterMinutes: 15,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("09:00", "18:00", [0, 6]),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email"],
            reminderLeadHours: [24, 168],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#4A5D73",
            embedTitle: "Book a Consulting Session",
            introMessage: "Choose a consultation slot and share a few planning notes.",
            primaryActionLabel: "Request Session",
            showServiceSelector: true,
            showPartySize: false,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Request a Consulting Session",
            heroMessage: "Share your preferred timing and any planning context before we confirm your session.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your consultation request has been submitted.",
        }),
        suggestedResources: [
            { name: "Advisory Sessions", resourceType: "appointment", capacity: 1, durationMinutes: 60, requiresApproval: true },
            { name: "Consultant Team", resourceType: "staff", capacity: 1, durationMinutes: 60, requiresApproval: true },
        ],
    },
    {
        key: "venue",
        label: "Venue Bookings",
        description: "Longer reservation windows, event resources, and approval-ready scheduling defaults.",
        businessType: "venue",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 60,
            minAdvanceMinutes: 1440,
            maxAdvanceDays: 365,
            bufferBeforeMinutes: 60,
            bufferAfterMinutes: 60,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("08:00", "23:00", []),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email"],
            reminderLeadHours: [24, 168],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#6D4C41",
            embedTitle: "Plan Your Event",
            introMessage: "Share your preferred date and event space to start the booking process.",
            primaryActionLabel: "Check Venue",
            showServiceSelector: true,
            showPartySize: true,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Start Planning Your Event",
            heroMessage: "Tell us about your preferred date, space, and guest count so we can prepare the right fit.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your venue request has been submitted for review.",
        }),
        suggestedResources: [
            { name: "Main Hall", resourceType: "event", capacity: 150, requiresApproval: true },
            { name: "Breakout Rooms", resourceType: "room", capacity: 25, requiresApproval: true },
        ],
    },
    {
        key: "rental",
        label: "Rental Inventory",
        description: "Longer resource holds for rental stock, with tighter buffers for pickup and return coordination.",
        businessType: "rental",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 60,
            minAdvanceMinutes: 180,
            maxAdvanceDays: 180,
            bufferBeforeMinutes: 30,
            bufferAfterMinutes: 30,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("08:00", "18:00", [0]),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email"],
            reminderLeadHours: [24, 72],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#556B2F",
            embedTitle: "Reserve Rental Equipment",
            introMessage: "Choose the inventory you need and the dates you want to hold it.",
            primaryActionLabel: "Reserve Rental",
            showServiceSelector: true,
            showPartySize: false,
            showNotes: true,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Reserve Rental Inventory",
            heroMessage: "Choose the equipment and dates you need, and we will confirm availability.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your rental request has been received.",
        }),
        suggestedResources: [
            { name: "Rental Inventory", resourceType: "equipment", capacity: 1, requiresApproval: false },
            { name: "Pickup Counter", resourceType: "appointment", capacity: 1, durationMinutes: 30, requiresApproval: false },
        ],
    },
    {
        key: "fitness",
        label: "Fitness Classes",
        description: "Recurring class-friendly slots with moderate buffers and a mix of staff and room suggestions.",
        businessType: "fitness",
        availabilityRules: createAvailabilityRules({
            slotIntervalMinutes: 30,
            minAdvanceMinutes: 60,
            maxAdvanceDays: 45,
            bufferBeforeMinutes: 10,
            bufferAfterMinutes: 10,
            allowOverbooking: false,
        }),
        workingHours: weekTemplate("06:00", "21:00"),
        notificationSettings: createNotificationSettings({
            enabledChannels: ["email", "sms"],
            reminderLeadHours: [2, 24],
            sendBookingConfirmation: true,
            sendCancellationNotice: true,
            sendRescheduleNotice: true,
        }),
        widgetSettings: createWidgetSettings({
            enabled: true,
            accentColor: "#1F7A5C",
            embedTitle: "Reserve Your Class",
            introMessage: "Choose a class or trainer slot and save your spot.",
            primaryActionLabel: "Reserve Spot",
            showServiceSelector: true,
            showPartySize: false,
            showNotes: false,
            showBusinessDescription: true,
        }),
        publicPageSettings: createPublicPageSettings({
            enabled: true,
            pageTitle: "Reserve Your Fitness Session",
            heroMessage: "Browse classes or trainers and save your preferred time slot.",
            showBusinessDescription: true,
            showAvailableResources: true,
            showContactDetails: true,
            showWorkingHours: true,
            confirmationMessage: "Your class reservation request has been received.",
        }),
        suggestedResources: [
            { name: "Class Studios", resourceType: "room", capacity: 20, requiresApproval: false },
            { name: "Trainer Schedule", resourceType: "staff", capacity: 1, durationMinutes: 60, requiresApproval: false },
        ],
    },
];

export const getBusinessTemplatePreset = (key: string): BusinessTemplatePreset | null => (
    businessTemplatePresets.find((template) => template.key === key) ?? null
);
